/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:f3c9991c-53cf-40b3-8d39-fbc3eeaa7bcd",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_H8YYU9O3p",
    "aws_user_pools_web_client_id": "21rld3n540khonsrb80o24ut6n",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://6y4epwaw5rd2hezt3itigym4ba.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
